# Generated by Django 3.0.1 on 2020-01-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Clientes'},
        ),
    ]
