# Generated by Django 3.0.1 on 2020-01-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_impresion',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Flexografica', 'Flexografica')], default='Digital', max_length=12),
        ),
    ]
