# Generated by Django 3.0.1 on 2020-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_auto_20200103_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='costo',
            field=models.FloatField(default=0),
        ),
    ]
