# Generated by Django 3.0.1 on 2020-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_cotizacion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_impresion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
