# Generated by Django 3.0.1 on 2020-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_cotizacion_tiempo_impresion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='tiempo_impresion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
