# Generated by Django 3.0.1 on 2020-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0008_auto_20200103_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='tiempo_impresion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
