# Generated by Django 3.0.1 on 2020-01-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0010_auto_20200103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='ancho',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='largo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
