# Generated by Django 3.0.1 on 2020-01-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0011_auto_20200104_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='ancho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='largo',
            field=models.FloatField(default=0),
        ),
    ]
