# Generated by Django 3.0.1 on 2020-01-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_impresora_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impresora',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='papel',
            options={'ordering': ['-id']},
        ),
    ]
